# Generated by Django 4.0.6 on 2022-07-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0004_alter_phone_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='slug',
            field=models.SlugField(verbose_name='URL'),
        ),
    ]
